### ISSUE TITLE
Remove ember-cli-htmlbars requirement?

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-template-imports/ember-template-imports#114]
this addon is giving a peer violation in [v2 addon blueprint](https://github.com/embroider-build/addon-blueprint/issues/100), and this addon is brought in via eslint-plugin-ember.

alternatively, eslint-plugin-ember (and ember-template-lint) could declare a `dependencies` entry on a wide range of supported (by template-imports) ember-cli-htmlbars.

**Comment by SergeAstapov** [comment]
@NullVoxPopuli should be fixed by #87, just not released yet

**Comment by NullVoxPopuli** [comment]
Merged in _November_? :thinking: 
is there more going in to this release? do folks want help managing releases? 
I think I've found a pretty good "no one needs access" process. Can demo :D

**Comment by chriskrycho** [comment]
I don't think there's any issue there (release-it handles it just fine)—people have just been in and out from vacation and hadn't had a pressing need. I'll bump it higher on the queue.

**Comment by NullVoxPopuli** [comment]
how's it going?
is this queue public?
can I help with busfactor? 
(if release were automated on GitHub, then than improves busfactor 🎉 )

**Comment by NullVoxPopuli** [comment]
With [3.4.1](https://github.com/ember-template-imports/ember-template-imports/commit/7d395a2c33f4ad94ff2cb2f98d65b3ad777a857c) released, I'll close this and open new issues (if I encounter them) for this version

**Comment by chriskrycho** [comment]
Thanks!
