### ISSUE TITLE
Add gjs/gts highlighting to GitHub

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-template-imports/ember-template-imports#123]
We need 200 unique repos before they'll accept a PR:

https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language 
https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language

[Here is a search](https://cs.github.com/?scopeName=All+repos&scope=&q=%28path%3A*.gjs+OR+path%3A*.gts%29+AND+content%3A%40ember) for all the gjs/gts files currently on GitHub.
at this time, I don't know how to count repos from these results -- the repos mentioned on the right-hand side of the page feel very incomplete.

**Comment by wagenet** [comment]
Do private repos count?

**Comment by dfreeman** [comment]
For what it's worth, I've been using [this search](https://cs.github.com/?scopeName=All+repos&scope=&q=path%3A%2F%5C.%28gjs%7Cgts%29%24%2F+%3Ctemplate%3E) which returns a few more hits, all of which are legitimate as far as I can tell.

It looks like Code Search will only give you the first 100 results, though, so I wonder if the repo list there is just the repositories that contain those hits?

> Do private repos count?

I've hunted for an answer to that question in the past and haven't been able to find one. Might be worth asking somewhere?

**Comment by gitKrystan** [comment]
Per the github-linguist documentation, the rule for adding a new extension is _usually_ the following:

> We try only to add new extensions once they have some usage on GitHub. In most cases we prefer that each new file extension be in use in at least 200 unique `:user/:repo` repositories before supporting them in Linguist.
>
> _-- [CONTRIBUTING.md](https://github.com/github-linguist/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language)_

But, the way they were using to determine "200 unique `:user/:repo` repositories" is in flux with the new GitHub code search feature, so they are temporarily using the following rules as a proxy of determining the above:

> * at least 2000 files per extension indexed in the last year (the number you see at the top of the search results), unless the extension is expected to only occur once per repo, then 200 files.
> * with a reasonable distribution across unique `:user/:repo` combinations assessed by manually and randomly clicking through the results.
>
> _-- [github-linguist/linguist#5756](https://github.com/github-linguist/linguist/issues/5756)_

Using a quick search, it looks like there are currently over 900 gjs/gts files on GitHub: [search: "(path:*.gjs OR path:*.gts) AND (content:@ember OR content:@glimmer OR content:\<template\>) "](https://github.com/search?q=%28path%3A*.gjs+OR+path%3A*.gts%29+AND+%28content%3A%40ember+OR+content%3A%40glimmer+OR+content%3A%3Ctemplate%3E%29+&type=code)

(Notably, there is already support for _another_ .gts extension--Gerber file--but we should be able to disambiguate, as I've done in the search above and following [these docs](https://github.com/github-linguist/linguist/blob/master/CONTRIBUTING.md#fixing-a-misclassified-language). @wycats noted that Gerber files seem to always start with "G0X" and have lines starting with "%".)

In the meantime, @wagenet noted a way to use the documented [override strategies](https://github.com/github-linguist/linguist/blob/master/docs/overrides.md) to get at least the JS/TS portion of a gts/gjs file highlighted. Just add the following to a `.gitattributes` file in the top level of the repository:

```
*.gjs linguist-language=js linguist-detectable
*.gts linguist-language=ts linguist-detectable
```

Example:
![image](https://github.com/ember-template-imports/ember-template-imports/assets/14152574/1a60b0bd-f5a0-4fed-92ec-58efc09fb8d3)

**Comment by NullVoxPopuli** [comment]
I think we should include markdown codefences in our search, via this:

https://github.com/search?q=%28%28path%3A*.gjs+OR+path%3A*.gts%29+AND+%28content%3A%3Ctemplate%3E%29%29+OR+%28path%3A*.md+AND+content%3A%3Ctemplate%3E+AND+content%3Agjs%29%29&type=code

This puts us at 1.8k files, which is ~ 200 short of the required 2000.

**Comment by gilest** [comment]
Draft PR for adding gts/gjs highlighting support to GitHub. Getting feedback here before I target the upstream Lingust repo https://github.com/gilest/linguist/pull/1

**Comment by gilest** [comment]
PR opened github-linguist/linguist/pull/6556

**Comment by jakebixby** [comment]
> I think we should include markdown codefences in our search, via this:
> 
> [github.com/search?q=%28%28path%3A*.gjs+OR+path%3A*.gts%29+AND+%28content%3A%3Ctemplate%3E%29%29+OR+%28path%3A*.md+AND+content%3A%3Ctemplate%3E+AND+content%3Agjs%29%29&type=code](https://github.com/search?q=%28%28path%3A*.gjs+OR+path%3A*.gts%29+AND+%28content%3A%3Ctemplate%3E%29%29+OR+%28path%3A*.md+AND+content%3A%3Ctemplate%3E+AND+content%3Agjs%29%29&type=code)
> 
> This puts us at 1.8k files, which is ~ 200 short of the required 2000. (this includes vue... so.. 🙃 )
> 
> If I try to exclude mentions of vue, that puts us back down at 1200 for now: [github.com/search?q=%28%28path%3A*.gjs+OR+path%3A*.gts%29+AND+%28content%3A%3Ctemplate%3E%29%29+OR+%28path%3A*.md+AND+content%3A%3Ctemplate%3E+AND+content%3Agjs+AND+%28NOT+content%3Avue%29%29%29&type=code](https://github.com/search?q=%28%28path%3A*.gjs+OR+path%3A*.gts%29+AND+%28content%3A%3Ctemplate%3E%29%29+OR+%28path%3A*.md+AND+content%3A%3Ctemplate%3E+AND+content%3Agjs+AND+%28NOT+content%3Avue%29%29%29&type=code)
> 
> I have more gjs/gts tests to write.

It's odd that adding the markdown bit to the query reduces the count, whereas I see 2.3k files, which I would assume meets the threshold? https://github.com/search?q=((path:*.gjs+OR+path:*.gts)+AND+(content:%3Ctemplate%3E))&type=code

**Comment by NullVoxPopuli** [comment]
Looks like there was a syntax issue the the previous markdown query.

Fixed here: 
https://github.com/search?q=%28%28path%3A*.gjs+OR+path%3A*.gts%29+AND+%28content%3A%3Ctemplate%3E%29%29+OR+%28path%3A*.md+AND+content%3A%3Ctemplate%3E+AND+%28%28content%3Agjs+OR+content%3Agts%29+AND+%28NOT+content%3Avue%29%29%29&type=code

Which gives us 2.7k files

**Comment by fdeters** [comment]
Just saw that Glimmer JS is supported as of [`github-linguist` v7.28.0](https://github.com/github-linguist/linguist/releases/tag/v7.28.0) 🎉

Syntax highlighting is working in my repos, but looks like we're still waiting to see Glimmer JS in the language breakdown chart.

**Comment by deanylev** [comment]
@fdeters seems to only be for `.gjs` files, not `.gts` files 😕

**Comment by NullVoxPopuli** [comment]
This is done!
