### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by josemarluedke** [ember-template-imports/ember-template-imports#14]
Currently, we cannot use the hbs template literal with TypeScript files.

The problem is that TS removes unused imports, so all the components/helpers/modifiers that are imported for a given component gets removed, resulting in error due to not having these definitions.

As a workaround, we can fakely pass the scope variables. NOTE: They don't do anything rather than making TS keep the imports.

```ts
import Component from '@glimmer/component';
import { action } from '@ember/object';
import { hbs } from 'ember-template-imports';
import { Button } from './other/bla';
import { on } from '@ember/modifier';

export default class Hello extends Component {
  name = 'world';

  @action
  doSomething() {
    console.log('action called');
  }

  static template = hbs(
    `
    <span>Hello, {{this.name}}!</span>
    <Button class="button" {{on "click" this.doSomething}}>Cool</Button>
  `,
    { scope: { Button, on } }
  );
}
```

While this workaround works, this is not ideal, therefore we should have better support for typescript users.

**Comment by knownasilya** [comment]
Does .gts work?

**Comment by chriskrycho** [comment]
This will likely need to be solved via Glint, both the LS and the CLI integration, which we can teach how to understand these files (and indeed: it already works with this basic format courtesy of glimmer-experimental).

**Comment by NullVoxPopuli** [comment]
Closing per RFC 779, and v4 of ETI. Hbs isn't supported anymore. Thank you for reporting!
