### ISSUE TITLE
Template shorter than three characters crashes build

### ISSUE THREAD

**Issue by ef4** [ember-template-imports/ember-template-imports#160]
A template whose contents are shorter than three characters crashes the build:

```js
import Component from '@glimmer/component';
export default class CurrentYear extends Component {
  <template>12</template>
}
```

```
Build Error (broccoli-persistent-filter:Mapper) in pdpm-calc/components/current-year.gts

Cannot overwrite a zero-length range – use appendLeft or prependRight instead
```

Each of the short lengths: 0, 1, or 2 characters produces a slightly *different* exception.

**Comment by NullVoxPopuli** [comment]
Should be resolved in v4. Thanks for reporting!
If this is still an issue, lemme know and we can reopen.
