### ISSUE TITLE
Export the constants in utils file explicitly for lint tooling

### ISSUE THREAD

**Issue by chrisrng** [ember-template-imports/ember-template-imports#178]
Today we use a direct import of the `utils` file to support lint tooling (see https://github.com/ember-cli/eslint-plugin-ember/blob/master/lib/preprocessors/glimmer.js#L7 and https://github.com/ember-template-lint/ember-template-lint/blob/master/lib/extract-templates.js#L2 for examples)

Since https://github.com/ember-template-imports/ember-template-imports/pull/78 mentions that this utils export will go away in the next major version we need to explicitly export it instead from `ember-template-imports`

**Comment by patricklx** [comment]
utils will not be needed in thr feature as hbs templates are deprecated and only template tag will be used.
https://github.com/embroider-build/content-tag/tree/main needs to expose template location information.
I also created a babel version of it. Which is here: https://github.com/patricklx/ember-template-preprocessor and already exposes that information
