### ISSUE TITLE
preprocessEmbeddedTemplates appears to be processing jsdoc comments

### ISSUE THREAD

**Issue by gitKrystan** [ember-template-imports/ember-template-imports#183]
I'm not 100% sure ^^^ is what is happening.

I'm getting this report on my prettier plugin:

> JS comments are being parsed by the plugin, and if the plugin finds invalid syntax, it throws errors. This is common in our codebase when people write example usages of a component invocation, and it even catches on some JSDoc comments. really, any JS comment with `{{` will attempt to be parsed by the plugin.
> 
> example: this JSDoc comment with a type annotation containing an object, which _looks_ like a double-curly template invocation:
> ```
>   /**
>    * Error message from loading the suggestions and whether the user can retry.
>    * @type {{ errorMessage: string, canRetry: boolean} | undefined }}
>    */
> ```
> this breaks the prettier plugin
> ```
> ✖ yarn prettier:
> [error] packages/addons/profile-shared/addon/components/generated-suggestions/generated-suggestion-edit-view.gjs: SyntaxError: Unexpected token (544:9)
> [error]   542 |
> [error]   543 |
> [error] > 544 |  export default [__GLIMMER_TEMPLATE(`{{!voyager-i18n-resource}}
> [error]       |         ^
> [error]   545 | {{t-def "Original" key="i18n_original"}}
> [error]   546 | {{t-def "Dismiss" key="i18n_dismiss"}}
> [error]   547 | {{t-def "Something went wrong. Please try again." key="failure_toast"}}
> ```
> 
> something about the double-curly in the comment block is throwing off prettier, because when i delete that line it works fine
> - https://github.com/gitKrystan/prettier-plugin-ember-template-tag/issues/84

The plugin just passes the file contents to `preprocessEmbeddedTemplates` though:

https://github.com/gitKrystan/prettier-plugin-ember-template-tag/blob/1ab2de020a80cb507d69007aeaf6901b3f654221/src/parse.ts#L56-L66

**Comment by NullVoxPopuli** [comment]
This API has been removed in v4. You'll want to use content-tag for low level tooling work.
