### ISSUE TITLE
v4 is not working for select environments

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-template-imports/ember-template-imports#207]
Placeholder issue to have details later

Some discussion: https://github.com/ember-template-imports/ember-template-imports/pull/206/

**Comment by ef4** [comment]
This is caused by https://github.com/emberjs/babel-plugin-ember-template-compilation/pull/30

**Comment by NullVoxPopuli** [comment]
This is resolved.

For folks who run in to any issues with v4, make sure that your lockfile states that babel-plugin-ember-template-compilation is at least 2.2.1.
if it's not, delete the entry in the lockfile and re-run your package manager -- that should update it.

**Comment by lukemelia** [comment]
To aid future searchers like me: the advice in this ticket fixed an issue for me when using ember-template-imports v4 in a v1 addon, imports referenced within template tags were removed / elided / missing.
