### ISSUE TITLE
no-unused-expressions

### ISSUE THREAD

**Issue by amk221** [ember-template-imports/ember-template-imports#226]
Unsure if this is the right repo, appologies if wrong.

Class based `gjs` files get linted fine. But template only `gjs` files fail like this:

<img src="https://github.com/ember-template-imports/ember-template-imports/assets/382061/1da5bdd7-0838-4546-a51d-14b465c1118d" width="649">

**Comment by NullVoxPopuli** [comment]
You'd want to report over at the eslint plugin:
https://github.com/ember-cli/eslint-plugin-ember

Along with the versions of everything you're using, config, and if possible, a reproduction repo.

Thanks!

**Comment by amk221** [comment]
Linking https://github.com/ember-cli/eslint-plugin-ember/issues/2035
