### ISSUE TITLE
Setting `enableTypeScriptTransform` to true breaks imports in .gjs tests

### ISSUE THREAD

**Issue by azhiv** [ember-template-imports/ember-template-imports#228]
I'm trying to add TS declarations to our V2 addon and to modify the `test-app` so that it properly consumes those declarations. The initial state of the repository was as follows:
- the V2 addon has no *.d.ts files
- the test-app has no TS support, however it has a .gjs test file which runs successfully

I then followed [this](https://typed-ember.gitbook.io/glint/environments/ember/authoring-addons#adding-glint-types-to-addons-not-written-in-typescript) instruction to add declaration files to the addon.
The problem is when I add TS-related dependencies to the `test-app` (all source files extensions are preserved) and set `'ember-cli-babel': { enableTypeScriptTransform: true },` in `ember-cli-build.js`, the tests start failing with a very generic error "Could not find module `<addon-name>` imported from `test-app/tests/integration/helpers/<gjs-test>`". [Here's](https://github.com/retailnext/ember-bem-helpers/pull/187) the PR which reproduces the error, [this](https://github.com/retailnext/ember-bem-helpers/actions/runs/7574055305/job/20627601053?pr=187) is the exact test output.

Note that without setting `'ember-cli-babel': { enableTypeScriptTransform: true },` the **tests succeed**. Please also note that `ember-cli-typescript` is omitted.

Am I missing some piece of configuration?

PS: This is the difference in the output tree before and after setting `enableTypeScriptTransform`:

<img width="332" alt="Screenshot 2024-01-18 at 18 12 07" src="https://github.com/ember-template-imports/ember-template-imports/assets/32125472/d9399aba-d091-45a1-902d-07340c2bc9be">
<img width="279" alt="Screenshot 2024-01-18 at 18 11 24" src="https://github.com/ember-template-imports/ember-template-imports/assets/32125472/0384a5b7-f14d-411a-a2fd-d22ba66fbd2c">

**Comment by NullVoxPopuli** [comment]
Thanks for reporting, I'll look in to this, as I believe this may be the issue I'm seeing in a work-related project!

**Comment by NullVoxPopuli** [comment]
So far, I've noticed that the issue report is _only_ in classic (broccoli-only) mode -- `@embroider/webpack` (and `@embroider/vite`) do not have this issue.

**Comment by azhiv** [comment]
@NullVoxPopuli Is there a workaround for this, e.g. switching to the above mentioned bundlers?

**Comment by NullVoxPopuli** [comment]
right now the only work around I know of is to use v3 of template-imports. I have a hunch the babel config we have with ember-cli-babel may not be playing well with v4 of template-imports.

Sorry it took so long to reply, this week's been nuts

**Comment by andreyfel** [comment]
Seems that the issue is resolved now with the latest release of babel-plugin-ember-template-compilation after this change https://github.com/emberjs/babel-plugin-ember-template-compilation/pull/34

**Comment by NullVoxPopuli** [comment]
Confirmed!
