### ISSUE TITLE
GJS/GTS components break when rendering an `<svg>` that contains `<linearGradient>`

### ISSUE THREAD

**Issue by achambers** [ember-template-imports/ember-template-imports#229]
👋 Hi.

I think I've raised this in the correct repo. If not, let me know where is the appropriate place and I'll raise it there.

It seems that when I try and render an inline svg that includes a `<linearGradient>`, the app blows up with:

```js
Uncaught ReferenceError: linearGradient is not defined
    at Object.scope (my-app.js:67:21)
    at meta (vendor.js:30351:34)
    at compilable (vendor.js:31418:51)
    at TemplateImpl.asLayout (vendor.js:31641:28)
    at ConstantsImpl.resolvedComponent (vendor.js:31853:165)
    at resolveComponent (vendor.js:29533:22)
    at encodeOp (vendor.js:29856:18)
    at pushOp (vendor.js:31448:7)
    at vendor.js:31180:7
    at Compilers.compile (vendor.js:30153:7)
```

I have made a minimal reproduction here: https://stackblitz.com/edit/ember-cli-editor-output-rvl1ph?file=app%2Ftemplates%2Fapplication.hbs

There are two components rendering svgs. One that works and one that does not.

This is the simple working svg that does not include a gradient
```html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100" height="100">
  <circle cx="50" cy="50" r="40" fill="#2ecc71" />
</svg>
```

This is the same circle with a gradient.
```html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100" height="100">
  <defs>
    <linearGradient id="gradient" x1="0%" y1="0%" x2="100%" y2="0%">
      <stop offset="0%" style="stop-color: #3498db" />
      <stop offset="100%" style="stop-color: #2ecc71" />
    </linearGradient>
  </defs>
  <circle cx="50" cy="50" r="40" fill="url(#gradient)" />
</svg>
```

The latter svg breaks with he error above.

I am using:

- "ember-template-imports": "^4.0.0",
- "ember-source": "~5.6.0",

**Comment by johanrd** [comment]
Hi. For reference, here is the same issue in the glimmer-vm repo: https://github.com/glimmerjs/glimmer-vm/issues/1550. 

I was not sure where to post it, either:)

**Comment by NullVoxPopuli** [comment]
Repro:
https://limber.glimdown.com/edit?c=MQAgygag4gUDCSBnRBXApogXDAtCABogC4D2ADviGgDZoC2aAdkSAJaIgBO9JAbmgBNcIAMYBDRgHIWKRGlElG-Zq0UgSAMwLVWjNGM5ROYgayZF8cfNYDmAKw47%2BMADxF6ZamPcA%2BGCBAXRF4bfwCQXjMAdwAhEgAPAF4AIgAGEHSARizU5LCA%2BLpqRkQUgAsiIjJMAHoaqIaAOiiAZkaSThsagCZUvprgmzzwkELirHidRgBrcsrquoao5raOrsyATi2ayd1p5L8RlwE0DURDkcCp-U7jU3M2ARS6AE8jEzNmZJAbO8%2BiAAqxhKGg6dBSnBIRG8aAAFBtUgBKA75S5BUhkdQaM5oIgpACsAFJvsRyDgRCRqB0UjZKQJvjULpdAqTMZocXjkhsiSSMeTKdTktx6SBGaiAi4atcDL8PuYmYEaiczhdUS4RKxOCJaKIksl8d8RC8Cd9OCkACzfDSsajUFIoTjUWGSYCvd73ZiSZGii6SwZ%2BMJBF5EWgKwYAGhAACofJgymJELDBoiQABvcUgMpoVg2CqYEDZVKEgDcqIAvoGBsHQ64au46J4YX5rJYgA&format=glimdown

**Comment by simonihmig** [comment]
I think this can be closed, as https://github.com/emberjs/babel-plugin-ember-template-compilation/pull/33 fixes this issue. Make sure to update your lockfile to have `babel-plugin-ember-template-compilation@2.2.2`!

I did however see some other regressions with that version, will report over there. Just mentioning, as this might block upgrading for now...
