### ISSUE TITLE
astro components style?

### ISSUE THREAD

**Issue by lifeart** [ember-template-imports/ember-template-imports#23]
https://docs.astro.build/core-concepts/astro-components

https://github.com/snowpackjs/astro/tree/main/packages/astro-parser

![image](https://user-images.githubusercontent.com/1360552/126680171-c13b7a9e-e3fd-4519-8e90-0b0b2e3f1b56.png)

**Comment by NullVoxPopuli** [comment]
Closing, per rfc 779
