### ISSUE TITLE
upgrading 3 to 4 breaks

### ISSUE THREAD

**Issue by basz** [ember-template-imports/ember-template-imports#233]
```
-    "ember-template-imports": "3.4.2",
+    "ember-template-imports": "4.1.0",
```

Suddenly lots of import issues. 

in a .gts

`import { LinkTo } from '@ember/routing';`

`logo.ts:60 Uncaught (in promise) ReferenceError: LinkTo is not defined`

or (via /tests)

`import didInsert from '@ember/render-modifiers/modifiers/did-insert';`

`Uncaught (in promise) ReferenceError: didInsert is not defined`

**Comment by NullVoxPopuli** [comment]
Should be resolved now: https://github.com/ember-template-imports/ember-template-imports/issues/228#issuecomment-2066094190
