### ISSUE TITLE
Update `TemplateLiteralMatch` to include source `importPath` and `importIdentifier`

### ISSUE THREAD

**Issue by rwjblue** [ember-template-imports/ember-template-imports#42]
## Problem

As we continue to flesh out the shared usage of this library amongst various community tooling, I realized that in order to handle the different types of recompilation that the caller has to call `parseTemplates` multiple times in order to know how each template needs to be processed.

For example, when `ember-template-lint` processes inline templates, it will need to know if a given template should be considered "strict mode" or "loose mode" in order to enable the right set of template linting rules (e.g. `no-implicit-this`).  Right now, in order to do that `ember-template-lint` would have to process the same file twice:

```js
const strictTemplates = parseTemplates(someJsFileContents, 'app/components/foo.hbs', {
  templateLiteral: [
    { importPath: 'ember-template-imports', importSpecifier: 'hbs' }
  ]
});
const looseTemplates = parseTemplates(someJsFileContents, 'app/components/foo.hbs', {
  templateLiteral: [
    { importPath: 'ember-cli-htmlbars', importSpecifier: 'hbs' }
  ]
});
```

## Solution

Concretely, I think we should update the `TemplateLiteralMatch` to include the `importSpecifier` and `importPath` that they came from.

https://github.com/ember-template-imports/ember-template-imports/blob/8acb56937008a2e55807ba6f9f21146a5ccda058/src/parse-templates.ts#L13-L18

Should become:

```ts
export interface TemplateLiteralMatch {
  type: 'template-literal';
  tagName: string;
  start: RegExpMatchArray;
  end: RegExpMatchArray;
  importPath: string;
  importSpecifier: string;
}
```

This would allow `ember-template-lint` to all `parseTemplates` one time, and process each of the templates we find appropriately.

**Comment by nlfurniss** [comment]
Closed by #47
